//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCommerceImport.MagiConnect_Sales {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.magishop.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://www.magishop.com/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountCodeType", Namespace="http://www.magishop.com/")]
    public enum AccountCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalAccountCode = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactId = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.magishop.com/", ConfigurationName="MagiConnect_Sales.salesSoap")]
    public interface salesSoap {
        
        // CODEGEN: Generating message contract since element name Parameters from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/TestPing", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.TestPingResponse TestPing(ABCommerceImport.MagiConnect_Sales.TestPingRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/ExportOrders", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.ExportOrdersResponse ExportOrders(ABCommerceImport.MagiConnect_Sales.ExportOrdersRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/ExportOrdersUsingDateRange", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeResponse ExportOrdersUsingDateRange(ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/ExportShipments", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.ExportShipmentsResponse ExportShipments(ABCommerceImport.MagiConnect_Sales.ExportShipmentsRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/UpdateOrderStatus", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusResponse UpdateOrderStatus(ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/SetShipmentsToCompleted", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedResponse SetShipmentsToCompleted(ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/ExportProductQuantitiesForNewOrders", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersResponse ExportProductQuantitiesForNewOrders(ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/InsertOrder", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.AccountCodeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid))]
        ABCommerceImport.MagiConnect_Sales.InsertOrderResponse InsertOrder(ABCommerceImport.MagiConnect_Sales.InsertOrderRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/InsertOrderV2", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.AccountCodeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid))]
        ABCommerceImport.MagiConnect_Sales.InsertOrderV2Response InsertOrderV2(ABCommerceImport.MagiConnect_Sales.InsertOrderV2Request request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/UpdateOrder", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.AccountCodeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid))]
        ABCommerceImport.MagiConnect_Sales.UpdateOrderResponse UpdateOrder(ABCommerceImport.MagiConnect_Sales.UpdateOrderRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/DeleteOrder", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.DeleteOrderResponse DeleteOrder(ABCommerceImport.MagiConnect_Sales.DeleteOrderRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/InsertOrderItem", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.AccountCodeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid))]
        ABCommerceImport.MagiConnect_Sales.InsertOrderItemResponse InsertOrderItem(ABCommerceImport.MagiConnect_Sales.InsertOrderItemRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/UpdateOrderItem", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ABCommerceImport.MagiConnect_Sales.AccountCodeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid))]
        ABCommerceImport.MagiConnect_Sales.UpdateOrderItemResponse UpdateOrderItem(ABCommerceImport.MagiConnect_Sales.UpdateOrderItemRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://www.magishop.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magishop.com/DeleteOrderItem", ReplyAction="*")]
        ABCommerceImport.MagiConnect_Sales.DeleteOrderItemResponse DeleteOrderItem(ABCommerceImport.MagiConnect_Sales.DeleteOrderItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestPingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestPing", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.TestPingRequestBody Body;
        
        public TestPingRequest() {
        }
        
        public TestPingRequest(ABCommerceImport.MagiConnect_Sales.TestPingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class TestPingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfString Parameters;
        
        public TestPingRequestBody() {
        }
        
        public TestPingRequestBody(ABCommerceImport.MagiConnect_Sales.ArrayOfString Parameters) {
            this.Parameters = Parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestPingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestPingResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.TestPingResponseBody Body;
        
        public TestPingResponse() {
        }
        
        public TestPingResponse(ABCommerceImport.MagiConnect_Sales.TestPingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class TestPingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfString TestPingResult;
        
        public TestPingResponseBody() {
        }
        
        public TestPingResponseBody(ABCommerceImport.MagiConnect_Sales.ArrayOfString TestPingResult) {
            this.TestPingResult = TestPingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportOrders", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ExportOrdersRequestBody Body;
        
        public ExportOrdersRequest() {
        }
        
        public ExportOrdersRequest(ABCommerceImport.MagiConnect_Sales.ExportOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class ExportOrdersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid FilterStatusID;
        
        public ExportOrdersRequestBody() {
        }
        
        public ExportOrdersRequestBody(string Login, string Password, System.Guid FilterStatusID) {
            this.Login = Login;
            this.Password = Password;
            this.FilterStatusID = FilterStatusID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportOrdersResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ExportOrdersResponseBody Body;
        
        public ExportOrdersResponse() {
        }
        
        public ExportOrdersResponse(ABCommerceImport.MagiConnect_Sales.ExportOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class ExportOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportOrdersResult;
        
        public ExportOrdersResponseBody() {
        }
        
        public ExportOrdersResponseBody(string ExportOrdersResult) {
            this.ExportOrdersResult = ExportOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportOrdersUsingDateRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportOrdersUsingDateRange", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeRequestBody Body;
        
        public ExportOrdersUsingDateRangeRequest() {
        }
        
        public ExportOrdersUsingDateRangeRequest(ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class ExportOrdersUsingDateRangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid FilterStatusID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime FromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime ToDate;
        
        public ExportOrdersUsingDateRangeRequestBody() {
        }
        
        public ExportOrdersUsingDateRangeRequestBody(string Login, string Password, System.Guid FilterStatusID, System.DateTime FromDate, System.DateTime ToDate) {
            this.Login = Login;
            this.Password = Password;
            this.FilterStatusID = FilterStatusID;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportOrdersUsingDateRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportOrdersUsingDateRangeResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeResponseBody Body;
        
        public ExportOrdersUsingDateRangeResponse() {
        }
        
        public ExportOrdersUsingDateRangeResponse(ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class ExportOrdersUsingDateRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportOrdersUsingDateRangeResult;
        
        public ExportOrdersUsingDateRangeResponseBody() {
        }
        
        public ExportOrdersUsingDateRangeResponseBody(string ExportOrdersUsingDateRangeResult) {
            this.ExportOrdersUsingDateRangeResult = ExportOrdersUsingDateRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportShipmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportShipments", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ExportShipmentsRequestBody Body;
        
        public ExportShipmentsRequest() {
        }
        
        public ExportShipmentsRequest(ABCommerceImport.MagiConnect_Sales.ExportShipmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class ExportShipmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public ExportShipmentsRequestBody() {
        }
        
        public ExportShipmentsRequestBody(string Login, string Password) {
            this.Login = Login;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportShipmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportShipmentsResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ExportShipmentsResponseBody Body;
        
        public ExportShipmentsResponse() {
        }
        
        public ExportShipmentsResponse(ABCommerceImport.MagiConnect_Sales.ExportShipmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class ExportShipmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportShipmentsResult;
        
        public ExportShipmentsResponseBody() {
        }
        
        public ExportShipmentsResponseBody(string ExportShipmentsResult) {
            this.ExportShipmentsResult = ExportShipmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderStatus", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusRequestBody Body;
        
        public UpdateOrderStatusRequest() {
        }
        
        public UpdateOrderStatusRequest(ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class UpdateOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Guid FromStatusID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Guid ToStatusID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OrderTrackingReference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OrderStatusMessage;
        
        public UpdateOrderStatusRequestBody() {
        }
        
        public UpdateOrderStatusRequestBody(string Login, string Password, System.Guid OrderID, System.Guid FromStatusID, System.Guid ToStatusID, string OrderTrackingReference, string OrderStatusMessage) {
            this.Login = Login;
            this.Password = Password;
            this.OrderID = OrderID;
            this.FromStatusID = FromStatusID;
            this.ToStatusID = ToStatusID;
            this.OrderTrackingReference = OrderTrackingReference;
            this.OrderStatusMessage = OrderStatusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderStatusResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusResponseBody Body;
        
        public UpdateOrderStatusResponse() {
        }
        
        public UpdateOrderStatusResponse(ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class UpdateOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateOrderStatusResult;
        
        public UpdateOrderStatusResponseBody() {
        }
        
        public UpdateOrderStatusResponseBody(string UpdateOrderStatusResult) {
            this.UpdateOrderStatusResult = UpdateOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetShipmentsToCompletedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetShipmentsToCompleted", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedRequestBody Body;
        
        public SetShipmentsToCompletedRequest() {
        }
        
        public SetShipmentsToCompletedRequest(ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class SetShipmentsToCompletedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ShipmentIDs_Commaseperated;
        
        public SetShipmentsToCompletedRequestBody() {
        }
        
        public SetShipmentsToCompletedRequestBody(string Login, string Password, string ShipmentIDs_Commaseperated) {
            this.Login = Login;
            this.Password = Password;
            this.ShipmentIDs_Commaseperated = ShipmentIDs_Commaseperated;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetShipmentsToCompletedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetShipmentsToCompletedResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedResponseBody Body;
        
        public SetShipmentsToCompletedResponse() {
        }
        
        public SetShipmentsToCompletedResponse(ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class SetShipmentsToCompletedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetShipmentsToCompletedResult;
        
        public SetShipmentsToCompletedResponseBody() {
        }
        
        public SetShipmentsToCompletedResponseBody(string SetShipmentsToCompletedResult) {
            this.SetShipmentsToCompletedResult = SetShipmentsToCompletedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportProductQuantitiesForNewOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportProductQuantitiesForNewOrders", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersRequestBody Body;
        
        public ExportProductQuantitiesForNewOrdersRequest() {
        }
        
        public ExportProductQuantitiesForNewOrdersRequest(ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class ExportProductQuantitiesForNewOrdersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public ExportProductQuantitiesForNewOrdersRequestBody() {
        }
        
        public ExportProductQuantitiesForNewOrdersRequestBody(string Login, string Password) {
            this.Login = Login;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportProductQuantitiesForNewOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportProductQuantitiesForNewOrdersResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersResponseBody Body;
        
        public ExportProductQuantitiesForNewOrdersResponse() {
        }
        
        public ExportProductQuantitiesForNewOrdersResponse(ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class ExportProductQuantitiesForNewOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportProductQuantitiesForNewOrdersResult;
        
        public ExportProductQuantitiesForNewOrdersResponseBody() {
        }
        
        public ExportProductQuantitiesForNewOrdersResponseBody(string ExportProductQuantitiesForNewOrdersResult) {
            this.ExportProductQuantitiesForNewOrdersResult = ExportProductQuantitiesForNewOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOrder", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.InsertOrderRequestBody Body;
        
        public InsertOrderRequest() {
        }
        
        public InsertOrderRequest(ABCommerceImport.MagiConnect_Sales.InsertOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class InsertOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CurrencyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccountCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Options;
        
        public InsertOrderRequestBody() {
        }
        
        public InsertOrderRequestBody(string Login, string Password, string OrderNumber, string CurrencyCode, string AccountCode, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject, string Options) {
            this.Login = Login;
            this.Password = Password;
            this.OrderNumber = OrderNumber;
            this.CurrencyCode = CurrencyCode;
            this.AccountCode = AccountCode;
            this.ColumnNames = ColumnNames;
            this.OrderObject = OrderObject;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOrderResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.InsertOrderResponseBody Body;
        
        public InsertOrderResponse() {
        }
        
        public InsertOrderResponse(ABCommerceImport.MagiConnect_Sales.InsertOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class InsertOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertOrderResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid MagicoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StatusCode;
        
        public InsertOrderResponseBody() {
        }
        
        public InsertOrderResponseBody(string InsertOrderResult, System.Guid MagicoID, string StatusCode) {
            this.InsertOrderResult = InsertOrderResult;
            this.MagicoID = MagicoID;
            this.StatusCode = StatusCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOrderV2", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.InsertOrderV2RequestBody Body;
        
        public InsertOrderV2Request() {
        }
        
        public InsertOrderV2Request(ABCommerceImport.MagiConnect_Sales.InsertOrderV2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class InsertOrderV2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CurrencyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ABCommerceImport.MagiConnect_Sales.AccountCodeType AccountCodeType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccountCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Options;
        
        public InsertOrderV2RequestBody() {
        }
        
        public InsertOrderV2RequestBody(string Login, string Password, string OrderNumber, string CurrencyCode, ABCommerceImport.MagiConnect_Sales.AccountCodeType AccountCodeType, string AccountCode, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject, string Options) {
            this.Login = Login;
            this.Password = Password;
            this.OrderNumber = OrderNumber;
            this.CurrencyCode = CurrencyCode;
            this.AccountCodeType = AccountCodeType;
            this.AccountCode = AccountCode;
            this.ColumnNames = ColumnNames;
            this.OrderObject = OrderObject;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOrderV2Response", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.InsertOrderV2ResponseBody Body;
        
        public InsertOrderV2Response() {
        }
        
        public InsertOrderV2Response(ABCommerceImport.MagiConnect_Sales.InsertOrderV2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class InsertOrderV2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertOrderV2Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid MagicoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StatusCode;
        
        public InsertOrderV2ResponseBody() {
        }
        
        public InsertOrderV2ResponseBody(string InsertOrderV2Result, System.Guid MagicoID, string StatusCode) {
            this.InsertOrderV2Result = InsertOrderV2Result;
            this.MagicoID = MagicoID;
            this.StatusCode = StatusCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrder", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.UpdateOrderRequestBody Body;
        
        public UpdateOrderRequest() {
        }
        
        public UpdateOrderRequest(ABCommerceImport.MagiConnect_Sales.UpdateOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class UpdateOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OrderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CurrencyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccountCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Options;
        
        public UpdateOrderRequestBody() {
        }
        
        public UpdateOrderRequestBody(string Login, string Password, System.Guid OrderID, string OrderNumber, string CurrencyCode, string AccountCode, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject, string Options) {
            this.Login = Login;
            this.Password = Password;
            this.OrderID = OrderID;
            this.OrderNumber = OrderNumber;
            this.CurrencyCode = CurrencyCode;
            this.AccountCode = AccountCode;
            this.ColumnNames = ColumnNames;
            this.OrderObject = OrderObject;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.UpdateOrderResponseBody Body;
        
        public UpdateOrderResponse() {
        }
        
        public UpdateOrderResponse(ABCommerceImport.MagiConnect_Sales.UpdateOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class UpdateOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateOrderResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StatusCode;
        
        public UpdateOrderResponseBody() {
        }
        
        public UpdateOrderResponseBody(string UpdateOrderResult, string StatusCode) {
            this.UpdateOrderResult = UpdateOrderResult;
            this.StatusCode = StatusCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrder", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.DeleteOrderRequestBody Body;
        
        public DeleteOrderRequest() {
        }
        
        public DeleteOrderRequest(ABCommerceImport.MagiConnect_Sales.DeleteOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class DeleteOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Options;
        
        public DeleteOrderRequestBody() {
        }
        
        public DeleteOrderRequestBody(string Login, string Password, System.Guid OrderID, string Options) {
            this.Login = Login;
            this.Password = Password;
            this.OrderID = OrderID;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrderResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.DeleteOrderResponseBody Body;
        
        public DeleteOrderResponse() {
        }
        
        public DeleteOrderResponse(ABCommerceImport.MagiConnect_Sales.DeleteOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class DeleteOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteOrderResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StatusCode;
        
        public DeleteOrderResponseBody() {
        }
        
        public DeleteOrderResponseBody(string DeleteOrderResult, string StatusCode) {
            this.DeleteOrderResult = DeleteOrderResult;
            this.StatusCode = StatusCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOrderItem", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.InsertOrderItemRequestBody Body;
        
        public InsertOrderItemRequest() {
        }
        
        public InsertOrderItemRequest(ABCommerceImport.MagiConnect_Sales.InsertOrderItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class InsertOrderItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderItemObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Options;
        
        public InsertOrderItemRequestBody() {
        }
        
        public InsertOrderItemRequestBody(string Login, string Password, string OrderNumber, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderItemObject, string Options) {
            this.Login = Login;
            this.Password = Password;
            this.OrderNumber = OrderNumber;
            this.ColumnNames = ColumnNames;
            this.OrderItemObject = OrderItemObject;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOrderItemResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.InsertOrderItemResponseBody Body;
        
        public InsertOrderItemResponse() {
        }
        
        public InsertOrderItemResponse(ABCommerceImport.MagiConnect_Sales.InsertOrderItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class InsertOrderItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertOrderItemResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid MagicoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StatusCode;
        
        public InsertOrderItemResponseBody() {
        }
        
        public InsertOrderItemResponseBody(string InsertOrderItemResult, System.Guid MagicoID, string StatusCode) {
            this.InsertOrderItemResult = InsertOrderItemResult;
            this.MagicoID = MagicoID;
            this.StatusCode = StatusCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderItem", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.UpdateOrderItemRequestBody Body;
        
        public UpdateOrderItemRequest() {
        }
        
        public UpdateOrderItemRequest(ABCommerceImport.MagiConnect_Sales.UpdateOrderItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class UpdateOrderItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid OrderItemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderItemObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Options;
        
        public UpdateOrderItemRequestBody() {
        }
        
        public UpdateOrderItemRequestBody(string Login, string Password, System.Guid OrderItemID, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderItemObject, string Options) {
            this.Login = Login;
            this.Password = Password;
            this.OrderItemID = OrderItemID;
            this.ColumnNames = ColumnNames;
            this.OrderItemObject = OrderItemObject;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderItemResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.UpdateOrderItemResponseBody Body;
        
        public UpdateOrderItemResponse() {
        }
        
        public UpdateOrderItemResponse(ABCommerceImport.MagiConnect_Sales.UpdateOrderItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class UpdateOrderItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateOrderItemResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StatusCode;
        
        public UpdateOrderItemResponseBody() {
        }
        
        public UpdateOrderItemResponseBody(string UpdateOrderItemResult, string StatusCode) {
            this.UpdateOrderItemResult = UpdateOrderItemResult;
            this.StatusCode = StatusCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrderItem", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.DeleteOrderItemRequestBody Body;
        
        public DeleteOrderItemRequest() {
        }
        
        public DeleteOrderItemRequest(ABCommerceImport.MagiConnect_Sales.DeleteOrderItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class DeleteOrderItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid OrderItemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Options;
        
        public DeleteOrderItemRequestBody() {
        }
        
        public DeleteOrderItemRequestBody(string Login, string Password, System.Guid OrderItemID, string Options) {
            this.Login = Login;
            this.Password = Password;
            this.OrderItemID = OrderItemID;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrderItemResponse", Namespace="http://www.magishop.com/", Order=0)]
        public ABCommerceImport.MagiConnect_Sales.DeleteOrderItemResponseBody Body;
        
        public DeleteOrderItemResponse() {
        }
        
        public DeleteOrderItemResponse(ABCommerceImport.MagiConnect_Sales.DeleteOrderItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.magishop.com/")]
    public partial class DeleteOrderItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteOrderItemResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StatusCode;
        
        public DeleteOrderItemResponseBody() {
        }
        
        public DeleteOrderItemResponseBody(string DeleteOrderItemResult, string StatusCode) {
            this.DeleteOrderItemResult = DeleteOrderItemResult;
            this.StatusCode = StatusCode;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface salesSoapChannel : ABCommerceImport.MagiConnect_Sales.salesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class salesSoapClient : System.ServiceModel.ClientBase<ABCommerceImport.MagiConnect_Sales.salesSoap>, ABCommerceImport.MagiConnect_Sales.salesSoap {
        
        public salesSoapClient() {
        }
        
        public salesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public salesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public salesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public salesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.TestPingResponse ABCommerceImport.MagiConnect_Sales.salesSoap.TestPing(ABCommerceImport.MagiConnect_Sales.TestPingRequest request) {
            return base.Channel.TestPing(request);
        }
        
        public ABCommerceImport.MagiConnect_Sales.ArrayOfString TestPing(ABCommerceImport.MagiConnect_Sales.ArrayOfString Parameters) {
            ABCommerceImport.MagiConnect_Sales.TestPingRequest inValue = new ABCommerceImport.MagiConnect_Sales.TestPingRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.TestPingRequestBody();
            inValue.Body.Parameters = Parameters;
            ABCommerceImport.MagiConnect_Sales.TestPingResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).TestPing(inValue);
            return retVal.Body.TestPingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.ExportOrdersResponse ABCommerceImport.MagiConnect_Sales.salesSoap.ExportOrders(ABCommerceImport.MagiConnect_Sales.ExportOrdersRequest request) {
            return base.Channel.ExportOrders(request);
        }
        
        public string ExportOrders(string Login, string Password, System.Guid FilterStatusID) {
            ABCommerceImport.MagiConnect_Sales.ExportOrdersRequest inValue = new ABCommerceImport.MagiConnect_Sales.ExportOrdersRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.ExportOrdersRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.FilterStatusID = FilterStatusID;
            ABCommerceImport.MagiConnect_Sales.ExportOrdersResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).ExportOrders(inValue);
            return retVal.Body.ExportOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeResponse ABCommerceImport.MagiConnect_Sales.salesSoap.ExportOrdersUsingDateRange(ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeRequest request) {
            return base.Channel.ExportOrdersUsingDateRange(request);
        }
        
        public string ExportOrdersUsingDateRange(string Login, string Password, System.Guid FilterStatusID, System.DateTime FromDate, System.DateTime ToDate) {
            ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeRequest inValue = new ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.FilterStatusID = FilterStatusID;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            ABCommerceImport.MagiConnect_Sales.ExportOrdersUsingDateRangeResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).ExportOrdersUsingDateRange(inValue);
            return retVal.Body.ExportOrdersUsingDateRangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.ExportShipmentsResponse ABCommerceImport.MagiConnect_Sales.salesSoap.ExportShipments(ABCommerceImport.MagiConnect_Sales.ExportShipmentsRequest request) {
            return base.Channel.ExportShipments(request);
        }
        
        public string ExportShipments(string Login, string Password) {
            ABCommerceImport.MagiConnect_Sales.ExportShipmentsRequest inValue = new ABCommerceImport.MagiConnect_Sales.ExportShipmentsRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.ExportShipmentsRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            ABCommerceImport.MagiConnect_Sales.ExportShipmentsResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).ExportShipments(inValue);
            return retVal.Body.ExportShipmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusResponse ABCommerceImport.MagiConnect_Sales.salesSoap.UpdateOrderStatus(ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusRequest request) {
            return base.Channel.UpdateOrderStatus(request);
        }
        
        public string UpdateOrderStatus(string Login, string Password, System.Guid OrderID, System.Guid FromStatusID, System.Guid ToStatusID, string OrderTrackingReference, string OrderStatusMessage) {
            ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusRequest inValue = new ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.OrderID = OrderID;
            inValue.Body.FromStatusID = FromStatusID;
            inValue.Body.ToStatusID = ToStatusID;
            inValue.Body.OrderTrackingReference = OrderTrackingReference;
            inValue.Body.OrderStatusMessage = OrderStatusMessage;
            ABCommerceImport.MagiConnect_Sales.UpdateOrderStatusResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).UpdateOrderStatus(inValue);
            return retVal.Body.UpdateOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedResponse ABCommerceImport.MagiConnect_Sales.salesSoap.SetShipmentsToCompleted(ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedRequest request) {
            return base.Channel.SetShipmentsToCompleted(request);
        }
        
        public string SetShipmentsToCompleted(string Login, string Password, string ShipmentIDs_Commaseperated) {
            ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedRequest inValue = new ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.ShipmentIDs_Commaseperated = ShipmentIDs_Commaseperated;
            ABCommerceImport.MagiConnect_Sales.SetShipmentsToCompletedResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).SetShipmentsToCompleted(inValue);
            return retVal.Body.SetShipmentsToCompletedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersResponse ABCommerceImport.MagiConnect_Sales.salesSoap.ExportProductQuantitiesForNewOrders(ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersRequest request) {
            return base.Channel.ExportProductQuantitiesForNewOrders(request);
        }
        
        public string ExportProductQuantitiesForNewOrders(string Login, string Password) {
            ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersRequest inValue = new ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            ABCommerceImport.MagiConnect_Sales.ExportProductQuantitiesForNewOrdersResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).ExportProductQuantitiesForNewOrders(inValue);
            return retVal.Body.ExportProductQuantitiesForNewOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.InsertOrderResponse ABCommerceImport.MagiConnect_Sales.salesSoap.InsertOrder(ABCommerceImport.MagiConnect_Sales.InsertOrderRequest request) {
            return base.Channel.InsertOrder(request);
        }
        
        public string InsertOrder(string Login, string Password, string OrderNumber, string CurrencyCode, string AccountCode, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject, string Options, out System.Guid MagicoID, out string StatusCode) {
            ABCommerceImport.MagiConnect_Sales.InsertOrderRequest inValue = new ABCommerceImport.MagiConnect_Sales.InsertOrderRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.InsertOrderRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.OrderNumber = OrderNumber;
            inValue.Body.CurrencyCode = CurrencyCode;
            inValue.Body.AccountCode = AccountCode;
            inValue.Body.ColumnNames = ColumnNames;
            inValue.Body.OrderObject = OrderObject;
            inValue.Body.Options = Options;
            ABCommerceImport.MagiConnect_Sales.InsertOrderResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).InsertOrder(inValue);
            MagicoID = retVal.Body.MagicoID;
            StatusCode = retVal.Body.StatusCode;
            return retVal.Body.InsertOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.InsertOrderV2Response ABCommerceImport.MagiConnect_Sales.salesSoap.InsertOrderV2(ABCommerceImport.MagiConnect_Sales.InsertOrderV2Request request) {
            return base.Channel.InsertOrderV2(request);
        }
        
        public string InsertOrderV2(string Login, string Password, string OrderNumber, string CurrencyCode, ABCommerceImport.MagiConnect_Sales.AccountCodeType AccountCodeType, string AccountCode, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject, string Options, out System.Guid MagicoID, out string StatusCode) {
            ABCommerceImport.MagiConnect_Sales.InsertOrderV2Request inValue = new ABCommerceImport.MagiConnect_Sales.InsertOrderV2Request();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.InsertOrderV2RequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.OrderNumber = OrderNumber;
            inValue.Body.CurrencyCode = CurrencyCode;
            inValue.Body.AccountCodeType = AccountCodeType;
            inValue.Body.AccountCode = AccountCode;
            inValue.Body.ColumnNames = ColumnNames;
            inValue.Body.OrderObject = OrderObject;
            inValue.Body.Options = Options;
            ABCommerceImport.MagiConnect_Sales.InsertOrderV2Response retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).InsertOrderV2(inValue);
            MagicoID = retVal.Body.MagicoID;
            StatusCode = retVal.Body.StatusCode;
            return retVal.Body.InsertOrderV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.UpdateOrderResponse ABCommerceImport.MagiConnect_Sales.salesSoap.UpdateOrder(ABCommerceImport.MagiConnect_Sales.UpdateOrderRequest request) {
            return base.Channel.UpdateOrder(request);
        }
        
        public string UpdateOrder(string Login, string Password, System.Guid OrderID, string OrderNumber, string CurrencyCode, string AccountCode, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderObject, string Options, out string StatusCode) {
            ABCommerceImport.MagiConnect_Sales.UpdateOrderRequest inValue = new ABCommerceImport.MagiConnect_Sales.UpdateOrderRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.UpdateOrderRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.OrderID = OrderID;
            inValue.Body.OrderNumber = OrderNumber;
            inValue.Body.CurrencyCode = CurrencyCode;
            inValue.Body.AccountCode = AccountCode;
            inValue.Body.ColumnNames = ColumnNames;
            inValue.Body.OrderObject = OrderObject;
            inValue.Body.Options = Options;
            ABCommerceImport.MagiConnect_Sales.UpdateOrderResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).UpdateOrder(inValue);
            StatusCode = retVal.Body.StatusCode;
            return retVal.Body.UpdateOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.DeleteOrderResponse ABCommerceImport.MagiConnect_Sales.salesSoap.DeleteOrder(ABCommerceImport.MagiConnect_Sales.DeleteOrderRequest request) {
            return base.Channel.DeleteOrder(request);
        }
        
        public string DeleteOrder(string Login, string Password, System.Guid OrderID, string Options, out string StatusCode) {
            ABCommerceImport.MagiConnect_Sales.DeleteOrderRequest inValue = new ABCommerceImport.MagiConnect_Sales.DeleteOrderRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.DeleteOrderRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.OrderID = OrderID;
            inValue.Body.Options = Options;
            ABCommerceImport.MagiConnect_Sales.DeleteOrderResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).DeleteOrder(inValue);
            StatusCode = retVal.Body.StatusCode;
            return retVal.Body.DeleteOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.InsertOrderItemResponse ABCommerceImport.MagiConnect_Sales.salesSoap.InsertOrderItem(ABCommerceImport.MagiConnect_Sales.InsertOrderItemRequest request) {
            return base.Channel.InsertOrderItem(request);
        }
        
        public string InsertOrderItem(string Login, string Password, string OrderNumber, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderItemObject, string Options, out System.Guid MagicoID, out string StatusCode) {
            ABCommerceImport.MagiConnect_Sales.InsertOrderItemRequest inValue = new ABCommerceImport.MagiConnect_Sales.InsertOrderItemRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.InsertOrderItemRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.OrderNumber = OrderNumber;
            inValue.Body.ColumnNames = ColumnNames;
            inValue.Body.OrderItemObject = OrderItemObject;
            inValue.Body.Options = Options;
            ABCommerceImport.MagiConnect_Sales.InsertOrderItemResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).InsertOrderItem(inValue);
            MagicoID = retVal.Body.MagicoID;
            StatusCode = retVal.Body.StatusCode;
            return retVal.Body.InsertOrderItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.UpdateOrderItemResponse ABCommerceImport.MagiConnect_Sales.salesSoap.UpdateOrderItem(ABCommerceImport.MagiConnect_Sales.UpdateOrderItemRequest request) {
            return base.Channel.UpdateOrderItem(request);
        }
        
        public string UpdateOrderItem(string Login, string Password, System.Guid OrderItemID, ABCommerceImport.MagiConnect_Sales.ArrayOfString ColumnNames, ABCommerceImport.MagiConnect_Sales.ArrayOfAnyType OrderItemObject, string Options, out string StatusCode) {
            ABCommerceImport.MagiConnect_Sales.UpdateOrderItemRequest inValue = new ABCommerceImport.MagiConnect_Sales.UpdateOrderItemRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.UpdateOrderItemRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.OrderItemID = OrderItemID;
            inValue.Body.ColumnNames = ColumnNames;
            inValue.Body.OrderItemObject = OrderItemObject;
            inValue.Body.Options = Options;
            ABCommerceImport.MagiConnect_Sales.UpdateOrderItemResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).UpdateOrderItem(inValue);
            StatusCode = retVal.Body.StatusCode;
            return retVal.Body.UpdateOrderItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCommerceImport.MagiConnect_Sales.DeleteOrderItemResponse ABCommerceImport.MagiConnect_Sales.salesSoap.DeleteOrderItem(ABCommerceImport.MagiConnect_Sales.DeleteOrderItemRequest request) {
            return base.Channel.DeleteOrderItem(request);
        }
        
        public string DeleteOrderItem(string Login, string Password, System.Guid OrderItemID, string Options, out string StatusCode) {
            ABCommerceImport.MagiConnect_Sales.DeleteOrderItemRequest inValue = new ABCommerceImport.MagiConnect_Sales.DeleteOrderItemRequest();
            inValue.Body = new ABCommerceImport.MagiConnect_Sales.DeleteOrderItemRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.OrderItemID = OrderItemID;
            inValue.Body.Options = Options;
            ABCommerceImport.MagiConnect_Sales.DeleteOrderItemResponse retVal = ((ABCommerceImport.MagiConnect_Sales.salesSoap)(this)).DeleteOrderItem(inValue);
            StatusCode = retVal.Body.StatusCode;
            return retVal.Body.DeleteOrderItemResult;
        }
    }
}
